### ISSUE TITLE
Increase margin between title and plots

### ISSUE THREAD

**Issue by MayaGans** [gaospecial/ggVennDiagram#15]
First of all thank you so much for this insanely incredible package! I was wondering if there's a way to increase the margin between titles and plots? [Ideally I'd like to move the `category_names` up a bit.

![image](https://user-images.githubusercontent.com/6053906/98845738-01e1a900-2403-11eb-94a0-effc8002fdc0.png)

Any help/tips appreciated!

**Comment by gaospecial** [comment]
This is really a shortage, but I am sorry currently it doesn't support adjust title margin. 

I have a alternative solution. You may export this graph to Powerpoint format. 

```r
# need export package
ggVenndiagram()
export::graph2ppt(file = "venn.pptx")
```

and then move the title by hand.
