### ISSUE TITLE
Show values in venn diagram (either as well as, or in place of counts and percentage)

### ISSUE THREAD

**Issue by williamlai2** [gaospecial/ggVennDiagram#16]
It would be good to be able to show values. 

Something like this (not sure if I am representing this correctly):

```
a <- c(1, 3) # A, AB
b <- c(1, 2) # AB, B

venn <- c(a[1], # A
          a[2] + b[1], # AB
          b[2]) # B

> venn
[1] 1 4 2
```

**Comment by williamlai2** [comment]
# #

**Comment by gaospecial** [comment]
## Showing intersection values

*Note: you need to install the GitHub version to enable these functions.*

We implemented the `get_region_items()` to get intersection values.

``` r
y <- list(
  A = sample(letters, 8),
  B = sample(letters, 8),
  C = sample(letters, 8),
  d = sample(letters, 8)
)

get_region_items(y)
#> $A
#> [1] "y" "b" "e"
#> 
#> $B
#> [1] "i" "v"
#> 
#> $C
#> [1] "a"
#> 
#> $D
#> [1] "h"
#> 
#> $AB
#> [1] "c"
#> 
#> $AC
#> character(0)
#> 
#> $AD
#> [1] "z"
#> 
#> $BC
#> [1] "d"
#> 
#> $BD
#> [1] "k"
#> 
#> $CD
#> [1] "f" "m"
#> 
#> $ABC
#> [1] "w"
#> 
#> $ABD
#> character(0)
#> 
#> $ACD
#> [1] "j"
#> 
#> $BCD
#> [1] "p"
#> 
#> $ABCD
#> [1] "x"
```

If only several items were included, intersections may also be viewed
interactively by `plotly` method (if you have two many items, this is
useless).

``` r
p <- ggVennDiagram(y, show_intersect = TRUE)
p
```

<img src="man/figures/README-unnamed-chunk-6-1.png" width="70%" />

``` r
plotly::ggplotly(p)
```

In web browser or RStudio, you will get:

<img src="https://vnote-1251564393.cos.ap-chengdu.myqcloud.com/typora-img/intersection.gif" width="70%" />
