### ISSUE TITLE
Can the circles/ellipses be scaled?

### ISSUE THREAD

**Issue by kopardev** [gaospecial/ggVennDiagram#17]
Here is what i get:
![image](https://user-images.githubusercontent.com/1882209/108254233-c30d6e80-7128-11eb-908c-9f96efa64414.png)
But here is what I want:
![image](https://user-images.githubusercontent.com/1882209/108254286-cf91c700-7128-11eb-99ca-693ff4806344.png)

**Comment by gaospecial** [comment]
ggVennDiagram didn't support scale currently.  For me, distinguishing parts by color is more intuitive than area. Besides, scaling is not applicable for Venn plot which has more than three eclipse.

However, `VennDiagram` has this feature, see https://cran.r-project.org/web/packages/VennDiagram/index.html  for more information.
