### ISSUE TITLE
formatting decimal places

### ISSUE THREAD

**Issue by mmpust** [gaospecial/ggVennDiagram#18]
Hello,
is it possible to change the number of decimal places displayed in the plot? I can see from your source code that you specified that two decimal places are shown (label=percentage). Can I define the number of decimal places (one or zero) when I call the function on my data frame?
Thanks,

Marie

**Comment by gaospecial** [comment]
It is now not supported. But you can still do it alternatively. 

The following is my solution:

1. Export the image to a PowerPoint slide through `exports`

```r
p <- ggVennDiagram()
exports::graph2ppt(p)
```

2. Now you can open it and edit the figure in PowerPoint.

**Comment by mmpust** [comment]
Okay, thanks nonetheless!

**Comment by mmpust** [comment]
Hello, 
do you plan on adding an optional argument for specifying the number of decimal points for percentage values soon? I would like to use your package for a publication image but I cannot use the figure with two decimal places because the level of precision is much too high and does mathematically make no sense in my case.
The option to convert it to a Powerpoint slide is not sufficient because I combine several plots with ggarrange in R and exporting it to a PowerPoint and then changing the numbers leads to a drop in the image quality. 

Do you have any other suggestions on what I could do to solve the problem?
Thanks in advance!

**Comment by gaospecial** [comment]
> Hello,
> do you plan on adding an optional argument for specifying the number of decimal points for percentage values soon? I would like to use your package for a publication image but I cannot use the figure with two decimal places because the level of precision is much too high and does mathematically make no sense in my case.
> The option to convert it to a Powerpoint slide is not sufficient because I combine several plots with ggarrange in R and exporting it to a PowerPoint and then changing the numbers leads to a drop in the image quality.
> 
> Do you have any other suggestions on what I could do to solve the problem?
> Thanks in advance!

I currently is developing a new generation of ggVennDiagram, and I intend to add this feature in TODO list. Before that, you may use the updated[ 0.5.1 ](https://github.com/gaospecial/ggVennDiagram/commit/030df7008f3304ee32669dc71dc68392d99dffff)version to finish this job.

```r
remotes::install_github("gaospecial/ggVennDiagram")
library("ggVennDiagram")
x <- list(A=1:5,B=2:7,C=3:6,D=4:9)
ggVennDiagram(x)
ggVennDiagram(x,percent_digits = 1)
```
![image](https://user-images.githubusercontent.com/107597/114329811-e675f800-9b72-11eb-89fe-b11bb8357f28.png)

![image](https://user-images.githubusercontent.com/107597/114329833-f392e700-9b72-11eb-92e5-e1c99cd32491.png)

Thanks for your choice of `ggVennDiagram`.
