### ISSUE TITLE
Create Clickable R shiny Venn Diagram

### ISSUE THREAD

**Issue by larry1995** [gaospecial/ggVennDiagram#25]
Hi Mr. Gao,

I am currently using your ggVennDiagram package. It's a great package for me to discover the relationship between my data. However, I wonder if there is any way that I can click on the Venn plot and return the exact gene list. E.g. I click on the intersection part and I will get a table of those genes. 
![image](https://user-images.githubusercontent.com/20786624/121300332-8cac5880-c8ab-11eb-99c1-91012ac96432.png)

Thank you for your help.

Sincerely,
Hao

**Comment by gaospecial** [comment]
You may show intersections with hovertext like this:

```r
gene_list <- list(A = sample(genes,100),
    B = sample(genes,200),
    C = sample(genes,300),
    D = sample(genes,200))
    library(ggVennDiagram)
    ggVennDiagram(gene_list, show_intersect = TRUE)
```

or use the function `get_region_items()` like this:

```r
venn = Venn(gene_list)
get_region_items(venn)
```
