### ISSUE TITLE
R crash when using ggVennDiagram()

### ISSUE THREAD

**Issue by mildpiggy** [gaospecial/ggVennDiagram#27]
My platform is Ubuntu 18.04, R version is 4.1.0.  When I used ggVennDiagram in rstudio-server, R will crash, reporting a R session Error: The previous R session was abnormally terminated due to an unexpected crash.
Is this package not support linux system?

**Comment by mildpiggy** [comment]
I have fixed the problem by just update RStudio-server from 1.4.1106 to lastest 1.4.1717. Because I find that not only ggVennDiagram but other Plots functions are crash in RStudio, however shiny-server works well. Maybe the old version RStudio isn't compatible with updated R.

**Comment by gaospecial** [comment]
@mildpiggy thanks for your feedback.
