### ISSUE TITLE
How do I remove zero count

### ISSUE THREAD

**Issue by archymedes** [gaospecial/ggVennDiagram#28]
I want to only plot non-zero count. I do not know how to access to the data and filter count > 0

**Comment by archymedes** [comment]
after d = Venn(data) and process_data(d), d is a S4 class object. S4 class objects can be accessed using `@`, so with d@region$count, a vector is returned, like any data.frame object

**Comment by gaospecial** [comment]
@archymedes **ggVennDiagram** has a function `region_data()` to access `d@region` data frame.
