### ISSUE TITLE
The label length of the sets cannot be customized

### ISSUE THREAD

**Issue by dqrsc** [gaospecial/ggVennDiagram#33]
sometimes label of each set is so long but important. the current version doesn't seem to be able to change the length of the label, tried 'scale_x_discrete' but it's not work.

for example, the raw label shown like this,

'phenotype_in_control_group_vs_phenotype_in_treated_group'

but i want it to look like this,

'phenotype_in_control_group_vs
_phenotype_in_treated_group'

**Comment by gaospecial** [comment]
here is a reproducible example.

```r
library(ggVennDiagram)
gene_list = lapply(1:4, function(x) sample(1:20, size = 10))
names(gene_list) = paste0("treated-",1:4,"-vs-control")
ggVennDiagram(gene_list)

# new list2
gene_list2 = gene_list
names(gene_list2) = stringr::str_wrap(names(gene_list),width = 8)
# label wrap
ggVennDiagram(gene_list2)
# axis expansion
ggVennDiagram(gene_list2) + 
  scale_x_continuous(expand = expansion(add = 0.2)) + 
  scale_y_continuous(expand = expansion(add=0.2)) 
```

If you want to control element, you need to perform step-wise self-definition, refer to <https://gaospecial.github.io/ggVennDiagram/articles/fully-customed.html>

However, if I were you, I would like to give a short name to the list, or export this graph to PPT using `export::graph2ppt()` to do further modification in PowerPoint.
