### ISSUE TITLE
Rotate the whole venn diagram

### ISSUE THREAD

**Issue by hjsbio** [gaospecial/ggVennDiagram#34]
Dear authors,

Is their any methods to rotate the whole venn diagram. For example, the default 3-sets venn is like below,
![image](https://user-images.githubusercontent.com/42362895/139621596-6a590d29-dee9-4866-9771-562450d96d80.png)

so how can we make it like this:
![image](https://user-images.githubusercontent.com/42362895/139621707-78decd58-a858-4a31-af59-7002d2b38378.png)

**Comment by gaospecial** [comment]
Using a different shape in ggVennDiagram is possible as you know how to setup a novel shapes for it, see <https://gaospecial.github.io/ggVennDiagram/articles/using-new-shapes.html> for more information.

By the way, I have changed the default shapes stored in ggVennDiagram's system data, therefore, you may install the developing version and run:

```r
remotes::install_github("gaospecial/ggVennDiagram")

l = list(A=1:3,B=2:4,C=3:6)
data = process_data(Venn(l), shape_id == "301f")
ggplot() +
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(aes(color = id), data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(aes(label = name), data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data)) +
  theme_void()
```

![image](https://user-images.githubusercontent.com/107597/139629694-858a8392-d7e6-432f-8b46-5af64de49678.png)

**Comment by hjsbio** [comment]
Dear author,
Thanks for your quick replay, I just checked it, it works. Terrific.

**Comment by hjsbio** [comment]
> Using a different shape in ggVennDiagram is possible as you know how to setup a novel shapes for it, see https://gaospecial.github.io/ggVennDiagram/articles/using-new-shapes.html for more information.
> 
> By the way, I have changed the default shapes stored in ggVennDiagram's system data, therefore, you may install the developing version and run:
> 
> ```r
> remotes::install_github("gaospecial/ggVennDiagram")
> 
> library(ggVennDiagram)
> library(ggplot2)
> l = list(A=1:3,B=2:4,C=3:6)
> data = process_data(Venn(l), shape_id == "301f")
> ggplot() +
>   geom_sf(aes(fill = count), data = venn_region(data)) +
>   geom_sf(aes(color = id), data = venn_setedge(data), show.legend = FALSE) +
>   geom_sf_text(aes(label = name), data = venn_setlabel(data)) +
>   geom_sf_label(aes(label = count), data = venn_region(data)) +
>   theme_void()
> ```
> 
> ![image](https://user-images.githubusercontent.com/107597/139629694-858a8392-d7e6-432f-8b46-5af64de49678.png)

It works, thanks for your quick reply. Terrific.
