### ISSUE TITLE
Colour by percentage

### ISSUE THREAD

**Issue by mmpust** [gaospecial/ggVennDiagram#35]
Hello,

I want to compare different Venn Diagrams and in each diagram, I show both count and percentage values, but I want to colour by percentage so that several Venn Diagrams can be compared. Is that possible?

Thank you so much!

Marie

**Comment by gaospecial** [comment]
Trust me, the plot colored by percentage is identical to that colored by counts.
😄

**Comment by mmpust** [comment]
Thank you for the quick reply. Of course, the plot colored by percentage is identical to that colored by counts. But if you compare two Venn Diagrams and one has, for example, 45 counts in group A, which makes up 10 % in total in this particular context, and another Venn Diagram has 140 counts in group A, but makes up 10 % in total of this diagram, then the colors are very different because of the different raw count values but the percentage values are the same. 

But your solution is already helpful. Thank you!

**Comment by gaospecial** [comment]
> Thank you for the quick reply. Of course, the plot colored by percentage is identical to that colored by counts. But if you compare two Venn Diagrams and one has, for example, 45 counts in group A, which makes up 10 % in total in this particular context, and another Venn Diagram has 140 counts in group A, but makes up 10 % in total of this diagram, then the colors are very different because of the different raw count values but the percentage values are the same.
> 
> But your solution is already helpful. Thank you!

You may find a solution in user-defined mode. Like:

```r
library(ggVennDiagram)
library(ggplot2)
l = list(A=1:3,B=2:4,C=3:6)
data = process_data(Venn(l))
ggplot() +
  geom_sf(aes(fill = percentage), data = venn_region(data) %>% mutate(percentage = count/sum(count))) +
  geom_sf(aes(color = id), data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(aes(label = name), data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data)) +
  theme_void()
```

see https://gaospecial.github.io/ggVennDiagram/articles/using-new-shapes.html for more information.
