### ISSUE TITLE
Can not change the color of edges

### ISSUE THREAD

**Issue by AnnaKaisanLahti** [gaospecial/ggVennDiagram#36]
Hi,

I can not change the color of the edges in ggVennDiagram:

ggVennDiagram(x_bac, color = "black", category.names = c("AM", "FE"), label_alpha = 0) +
scale_fill_gradient(low = "pink1", high = "pink4")

This works otherwise fine, but none of the commands to modify the edges have any effect(color, lty, lwd), and I get red border for AM set and light blue for FE set, no matter the settings.

I also tried the other way and this produces red edges to both sets, no matter the options:

venn <- Venn(x_bac)
data <- process_data(venn)
ggplot() +
geom_sf(aes(fill = count), data = venn_region(data)) +
geom_sf(aes(color="black"), data = venn_setedge(data), show.legend = FALSE) +
geom_sf_text(aes(label = name), data = venn_setlabel(data)) +
geom_sf_label(aes(label = count), data = venn_region(data)) +
theme_void()

What am I doing wrong here?

![Capture1](https://user-images.githubusercontent.com/94971381/143248108-9e725439-819a-4e08-82e3-d7aebf06cd09.JPG)
![Capture2](https://user-images.githubusercontent.com/94971381/143248111-8703ce76-7746-4fa6-b25b-850c654b3ced.JPG)

**Comment by gaospecial** [comment]
You may use `set_color` to set the color of set labels, and `scale_color_*()` function to set the color of edges.

for example,

```r
library(ggVennDiagram)
l = list(A=1:2,B=2:3,C=4:6,D=1:5)
ggVennDiagram(l, set_color = c("black","grey","yellow","green"))
```
![image](https://user-images.githubusercontent.com/107597/143328692-83b52aab-268b-4837-b20b-0a3efccb1e1b.png)


```r
ggVennDiagram(l, set_color = c("black","grey","yellow","green")) + scale_color_manual(values = c("black","blue","green","yellow"))
```

![image](https://user-images.githubusercontent.com/107597/143328707-362c7285-8dd7-4f2c-9a7d-1f18d93a4048.png)

**Comment by AnnaKaisanLahti** [comment]
Thank you! scale_color_*() worked like a charm.
