### ISSUE TITLE
Is it possible to show text?

### ISSUE THREAD

**Issue by jinghuazhao** [gaospecial/ggVennDiagram#38]
I just got to know your great package. 

I saw this diagram and is it possible to generate?

![EUR-NATO](https://user-images.githubusercontent.com/12497005/156744907-27aa85dc-0585-4897-8a4b-f5be2853e1d2.png)

**Comment by gaospecial** [comment]
文本在 Venn 图上的排列会比较复杂，目前只能实现简短的填充效果。请查阅：https://gaospecial.github.io/ggVennDiagram/articles/using-ggVennDiagram-cn.html#%E6%98%BE%E7%A4%BA%E5%8C%BA%E5%9F%9F%E4%B8%AD%E7%9A%84%E6%88%90%E5%91%98

**Comment by jinghuazhao** [comment]
谢谢回复。正如所言，这有些不寻常我们暂做为一个问题并期望将来会有一个好的算法解决。再次感谢开发这个包，我一直用VennDiagram而使用了ggplot2的设计会有不少灵活性。
