### ISSUE TITLE
Change color of edges

### ISSUE THREAD

**Issue by eggrandio** [gaospecial/ggVennDiagram#39]
Hi,

Is it possible to change the edge color without having to generate a `VennPlotData` object and customizing it? 

It seems that in older versions you could change it by specifying `color`, but it is no longer possible.

Example [here](https://r-charts.com/part-whole/ggvenndiagram/) does not produce a plot with black edges.
```
# install.packages("ggVennDiagram")
library(ggVennDiagram)
# install.packages("ggplot2")
library(ggplot2)

# List of items
x <- list(A = 1:5, B = 2:7, C = 5:10)

# Venn diagram with custom border
ggVennDiagram(x, color = "black", lwd = 0.8, lty = 1) + 
  scale_fill_gradient(low = "#F4FAFE", high = "#4981BF")
```

**Comment by gaospecial** [comment]
Maybe that is out of date. 

Changing edge color is possible if you use `scale_color_manual()`, please refer to: https://gaospecial.github.io/ggVennDiagram/
