### ISSUE TITLE
remove the background of text

### ISSUE THREAD

**Issue by ying-ge** [gaospecial/ggVennDiagram#4]
![1051572249007_ pic](https://user-images.githubusercontent.com/45988974/67660873-c2345480-f99a-11e9-977e-84b575ad5ee6.jpg)

Thank you for building this package. The code is user friendly.
Would you add an option that user can choose whether add background for text or not? Thank you very much.

**Comment by gaospecial** [comment]
Install the 0.3.1 version, which has a additional parameter of label_alpha.

set label_alpha = 0 to remove the background of labels.


`
devtools::install_github("gaospecial/ggVennDiagram")
ggVennDiagram(x, label_alpha=0)
`

**Comment by iMarcello** [comment]
Hi, unfortunately I've installed the last 0.32 version and this didn't work.

> ggVennDiagram(x, label_alpha=0)
Warning: Ignoring unknown parameters: label_alpha

**Comment by gaospecial** [comment]
> Hi, unfortunately I've installed the last 0.32 version and this didn't work.
> 
> > ggVennDiagram(x, label_alpha=0)
> > Warning: Ignoring unknown parameters: label_alpha

It works for me. 

I'll check it one more time if you could provide a reproducible example.

**Comment by iMarcello** [comment]
Hi Ying! I've just try again and really works fine. Probably some library updated in meantime.
Thanks a lot for your attention and congratulations for this nice library.
