### ISSUE TITLE
transform phyloseq object to a list?

### ISSUE THREAD

**Issue by marwa38** [gaospecial/ggVennDiagram#40]
Could you please let me know how to transform my phyloseq object to be accepted as input data to use ggVennDiagram?
Many thanks 
M

**Comment by gaospecial** [comment]
I am afraid that I can't answer your question until a reproducible example of your `phyloseq` object is provided.

**Comment by marwa38** [comment]
Dear  @gaospecial 
sorry for my late reply 
here is a phyloseq object in form of .rds (zipped)
[ps.prev.rooted.zip](https://github.com/gaospecial/ggVennDiagram/files/10121836/ps.prev.rooted.zip)
please let mem know
Cheers
M

**Comment by marwa38** [comment]
Hi @gaospecial again 
Incase more clarification is needed, I want to create Venn diagrams of ASVs for each group 
examples that I need to create from my above-shared dataset 
![image](https://user-images.githubusercontent.com/68851733/204784080-35fa8472-cfbf-419f-902e-f619fe73c702.png)
![image](https://user-images.githubusercontent.com/68851733/204784101-2c28475e-9019-49ca-9de8-2fb37a96b5a9.png)
![image](https://user-images.githubusercontent.com/68851733/204784128-23a6f3d6-9bd4-440e-a960-1178c517e94e.png)
Thanks 
M

**Comment by gaospecial** [comment]
FYI.

```
d = readRDS("ps.prev.rooted.rds")
sample = sample_data(d)
library(dplyr)
sample_origin = sample$sample  %>%  unique()

get_otu = function(x){
  otu = otu_table(x)
  otu_count = colSums(otu)
  otu_name = names(otu_count)
  otu_name[otu>0]
}

list = vector("list", length = 3)
list[[1]] = subset_samples(d, Sample == sample_origin[[1]]) %>% get_otu()
list[[2]] = subset_samples(d, Sample == sample_origin[[2]]) %>% get_otu()
list[[3]] = subset_samples(d, Sample == sample_origin[[3]]) %>% get_otu()


library(ggVennDiagram)
ggVennDiagram(list, category.names = sample_origin)
```

![image](https://user-images.githubusercontent.com/107597/205889727-34cc4453-2a8d-4027-9aa0-129b0fcbff84.png)
