### ISSUE TITLE
rotate of venn / special shapes not working

### ISSUE THREAD

**Issue by deprekate** [gaospecial/ggVennDiagram#44]
I am trying to get the special shape 201f to work, which is a 90 degree rotated 2 circle plot, but it seems to not work (I think it is doing a 180 in stead of a 90).  The other special shapes (like 401f) worked fine for me

```
x <- list(A = 1:5, B = 2:7)
data = process_data(Venn(x), shape_id == "201f")
ggplot() +
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(aes(color = id), data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(aes(label = name), data = venn_setlabel(data)) +
  geom_sf_label(aes(label = count), data = venn_region(data)) +
  theme_void()
```
![aww](https://user-images.githubusercontent.com/1821312/191140397-ae7b232f-f5b0-4c7e-859a-11086afdda3d.png)

**Comment by gaospecial** [comment]
I get a rotated figure with Ubuntu system.

![image](https://user-images.githubusercontent.com/107597/191241415-f861c982-5926-4ec6-8dd9-5589c6fe6f80.png)
