### ISSUE TITLE
Make intersection overlaps proportional

### ISSUE THREAD

**Issue by hermidalc** [gaospecial/ggVennDiagram#45]
How can I specify to ggVennDiagram to make intersection overlaps proportional? E.g. https://stackoverflow.com/questions/8713994/venn-diagram-proportional-and-color-shading-with-semi-transparency

**Comment by gaospecial** [comment]
> How can I specify to ggVennDiagram to make intersection overlaps proportional? E.g. https://stackoverflow.com/questions/8713994/venn-diagram-proportional-and-color-shading-with-semi-transparency

In this case, `venneuler` or `VennDiagram` do this job very well.
