### ISSUE TITLE
Cannot change path edges

### ISSUE THREAD

**Issue by aalexiev** [gaospecial/ggVennDiagram#47]
Hello,

Thank you for your package, it's very useful. I'm having trouble getting the edge color to change. It says online that color = "black" should do this, but no matter what, it still stays in the default ggplot2 colors for each edge color. 

Below is my code and I have attached the output graph I keep getting:

`
# make the data frame for graphing
paths <- list(WholeDataset = sign_cpglmALL$pathway, 
           F0 = sign_cpglm$pathway, 
           F1 = sign_cpglmF1$pathway, 
           F2 = sign_cpglmF2_2$pathway)

# graph a venn diagram of the data
ggVennDiagram(paths, category.names = c("Whole Dataset",
                                    "F0 Generation",
                                    "F1 Generation",
                                    "F2 Generation"),
              color = "black") + 
  scale_fill_gradient(low = "white", high = "red")
`

![Screen Shot 2023-02-13 at 3 18 56 PM](https://user-images.githubusercontent.com/8505956/218596247-623d8b46-b5a2-4dde-aa9b-4b9118dd9697.png)

The object I'm using as an input is a list of four character vectors representing pathway names for four data sets. Github won't let me include a .RDS object but here is the structure:

`
> str(paths)
List of 4
 $ WholeDataset: chr [1:54] "ARG.POLYAMINE.SYN..superpathway.of.arginine.and.polyamine.biosynthesis" "ARGSYN.PWY..L.arginine.biosynthesis.I..via.L.ornithine." "ARGSYN.PWY..L.arginine.biosynthesis.I..via.L.ornithine." "ARGSYNBSUB.PWY..L.arginine.biosynthesis.II..acetyl.cycle." ...
 $ F0          : chr [1:94] "ARGSYN.PWY..L.arginine.biosynthesis.I..via.L.ornithine." "ARGSYNBSUB.PWY..L.arginine.biosynthesis.II..acetyl.cycle." "BIOTIN.BIOSYNTHESIS.PWY..biotin.biosynthesis.I" "BIOTIN.BIOSYNTHESIS.PWY..biotin.biosynthesis.I" ...
 $ F1          : chr [1:81] "ANAGLYCOLYSIS.PWY..glycolysis.III..from.glucose." "ARGININE.SYN4.PWY..L.ornithine.biosynthesis.II" "ARGSYN.PWY..L.arginine.biosynthesis.I..via.L.ornithine." "ARGSYNBSUB.PWY..L.arginine.biosynthesis.II..acetyl.cycle." ...
 $ F2          : chr [1:139] "ANAEROFRUCAT.PWY..homolactic.fermentation" "ANAGLYCOLYSIS.PWY..glycolysis.III..from.glucose." "ARGSYN.PWY..L.arginine.biosynthesis.I..via.L.ornithine." "ARGSYN.PWY..L.arginine.biosynthesis.I..via.L.ornithine." ...
`

**Comment by gaospecial** [comment]
`color` is no longer support in current version. Try to use the following:

```r
x = list(A=1:3,B=3:8,C=4:9)
library(ggVennDiagram)
ggVennDiagram(x) + ggplot2::scale_color_manual(values = c("red","blue","black"))
```
