### ISSUE TITLE
return a list of each region

### ISSUE THREAD

**Issue by ying-ge** [gaospecial/ggVennDiagram#5]
Would you add a return list so that I can check which genes are there in each region.
For example, I want to know the overlap gene list, or genes specific in one group.

**Comment by gaospecial** [comment]
Good suggestion.

I have add a function to get the list of region items in [recent commit](https://github.com/gaospecial/ggVennDiagram/commit/949430a07711ab0e671ca4b81bb5f15ae0c6733a)

```
items <- get_region_items(x)
```

**Comment by ying-ge** [comment]
Great, now I can save the list into an Excel file with one region in one sheet:
`openxlsx::write.xlsx(get_region_items(x), filename))`
The regions name is ABC now. It would be more convenient if the region name is the  category.names.

**Comment by gaospecial** [comment]
I have a new idea of storing set data in the plot object, just like what `ggtree` did.

**Comment by ScaonE** [comment]
Any news about this feature? (aka where can I get the list for each interset in the venn object?)

**Comment by gaospecial** [comment]
see example of `?get_region_items`

**Comment by ScaonE** [comment]
After installing with 
`devtools::install_github("gaospecial/ggVennDiagram")`
Under R 4.2.1

It doesn't seem to load any get_region_items() function.

What I did is reading this this issue & c/c old get_region_items(), three_dimension_region_items() & multi_intersect() functions from [v0.5.0](https://github.com/gaospecial/ggVennDiagram/releases/tag/v0.5.0) into my script. But I wish I have soemting cleaner.
Which version of the package should I use to get access to get_region_items() ?

**Comment by gaospecial** [comment]
> After installing with `devtools::install_github("gaospecial/ggVennDiagram")` Under R 4.2.1
> 
> It doesn't seem to load any get_region_items() function.
> 
> What I did is reading this this issue & c/c old get_region_items(), three_dimension_region_items() & multi_intersect() functions from [v0.5.0](https://github.com/gaospecial/ggVennDiagram/releases/tag/v0.5.0) into my script. But I wish I have someting cleaner. Which version of the package should I use to get access to get_region_items() ?

use `ggVennDiagram:::get_region_items()`. Three colons in it.  

However, you may do this job in a new way. For example:

```
l = list(A=1:3,B=4:6,C=2:5,D=c(1L,2L,8L))
v = Venn(l)
d = process_data(v)
d %>% select(name, item)
```
