### ISSUE TITLE
edge_size is probably not working

### ISSUE THREAD

**Issue by osumpcheng** [gaospecial/ggVennDiagram#55]
Thank you for building this package. I was trying to change the edge size (line width, if that's the right place to go), and it was not working as I expected. I'm guessing if there is anything wrong with this setting. 
I'm using v 1.2.2

ggVennDiagram(venn_x,  label = "count", label_alpha=0, edge_size = 10000)+ scale_fill_gradient(low="white",high = "red")
![image](https://github.com/gaospecial/ggVennDiagram/assets/62575245/edcaa754-9b3f-4dea-8dc5-522454927266)

**Comment by gaospecial** [comment]
Thanks for your feedback. This problem has been solved in latest version. Install the development version by `remotes::install_github("gaospecial/ggVennDiagram")`, and try it again.

**Comment by osumpcheng** [comment]
great! thank you so much
