### ISSUE TITLE
`sf` dependency very heavy

### ISSUE THREAD

**Issue by romanzenka** [gaospecial/ggVennDiagram#56]
Hello,

I am installing your package in a constrained environment and realizing that the `sf` package is very complex, as it supports large amount of geographical data types. I think you are using only a tiny fraction of the `sf` package functionality - like drawing ellipses/polygons... would it be possible to drop this dependency and only use the few tiny functions to reduce the "weight" of your package?

**Comment by gaospecial** [comment]
Hi, @romanzenka. 

I also noticed this shortage. But unfortunately I don't have time to do such things. Maybe later.

If some others also support this action, please reply to let me know.

**Comment by romanzenka** [comment]
I looked into it deeper and it seems that `ggplot2` itself has this dependency. So we are probably out of luck, since we cannot cleanly separate that from ggplot2. I'll close this ticket, as this is too hard, we would need "ggplot2 without geospatial data" to pull this off.

**Comment by gaospecial** [comment]
Several functions of `sf` are used to generate region shapes. Since these shapes are reused, there are no need to generate from scratch every time, therefore, I do think about to store these shapes in `sysdata` thus remove the heavy dependences.

**Comment by romanzenka** [comment]
You know, you could do that, but since you depend on `ggplot2` and `ggplot2` itself depends on `sf`, it will not solve the problem at all. The problem being that on Linux, I had to install three separate geospatial data libraries just to draw a Venn diagram. But that is a problem of `ggplot2`, not you.

**Comment by gaospecial** [comment]
@romanzenka Hi, I removed the `sf` dependency in new release.

**Comment by romanzenka** [comment]
@gaospecial Seriously???? You are amazing!

**Comment by gaospecial** [comment]
> @gaospecial Seriously???? You are amazing!

Sure. Thanks for your issue. 💯
