### ISSUE TITLE
Is it possible to mark sole subsets inside the circles?

### ISSUE THREAD

**Issue by pwwang** [gaospecial/ggVennDiagram#57]
![image](https://github.com/gaospecial/ggVennDiagram/assets/1188067/b9251fd7-3c7b-40cd-b5fc-7734d9ba972a)

In the above plot, `A.a`, `B.b` and `C.c` are sole subsets (without overlaping with other groups). Is it possible?
We have 6 groups, but we only need a 3-group layout.

**Comment by gaospecial** [comment]
I am afraid you have to draw it by yourself. However, `ggVennDiagram` may be helpful in this procedure. Firstly, draw three-set Venn with `ggVennDiagram`, and then export it as a `.pptx` or `.pdf` and add subsets.

**Comment by pwwang** [comment]
Thanks for the reply. I was just wondering if there is a better way to do it. I implemented it using geom_sf_label.
