### ISSUE TITLE
ggVennDiagram pkg installation issue

### ISSUE THREAD

**Issue by sfd99** [gaospecial/ggVennDiagram#6]
Really looking forward to try 
the **ggVennDiagram** pkg. 

But **it will not install** in my
 - latest Rstudio, 
 - Ubuntu Linux 18.04  64bits
 - R 3.6.1
from either CRAN nor from:
devtools::install_github("gaospecial/ggVennDiagram")

Here's the Rstudio console output
with the installation error messages:

-----------------
> install.packages("ggVennDiagram")
Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
also installing the dependencies ‘units’, ‘sf’

trying URL 'https://cloud.r-project.org/src/contrib/units_0.6-5.tar.gz'
Content type 'application/x-gzip' length 959970 bytes (937 KB)
==================================================
downloaded 937 KB

trying URL 'https://cloud.r-project.org/src/contrib/sf_0.8-0.tar.gz'
Content type 'application/x-gzip' length 8607770 bytes (8.2 MB)
==================================================
downloaded 8.2 MB

trying URL 'https://cloud.r-project.org/src/contrib/ggVennDiagram_0.3.tar.gz'
Content type 'application/x-gzip' length 163551 bytes (159 KB)
==================================================
downloaded 159 KB

* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
** using staged installation
configure: units: 0.6-4
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -std=gnu++11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for error_at_line... yes
checking for gcc... gcc -std=gnu99
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... no
checking udunits2.h usability... no
checking udunits2.h presence... no
checking for udunits2.h... no
checking udunits2/udunits2.h usability... no
checking udunits2/udunits2.h presence... no
checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/tmp/RtmpruJp2n/R.INSTALL1cb671dba372/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/units’
Warning in install.packages :
  installation of package ‘units’ had non-zero exit status
ERROR: dependency ‘units’ is not available for package ‘sf’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status
ERROR: dependency ‘sf’ is not available for package ‘ggVennDiagram’
* removing ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6/ggVennDiagram’
Warning in install.packages :
  installation of package ‘ggVennDiagram’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpAMBDPc/downloaded_packages’

_Help!_
_I really want to try this out...what am I missing?._

**SFD99
San Francisco
 - latest Rstudio
 - Ubuntu Linux 18.04  64bits
 - R 3.6.1**

**Comment by gaospecial** [comment]
I think the error comes from that you failed to install a dependent package `units`. The reason is, by the message, you didn't have `libudunits2.so` ready in your operating system.

Try this and then reinstall ggVennDiagram.

`sudo apt-get install libudunits2-dev`

**Comment by sfd99** [comment]
*thank you Chun-Hui Gao!.*
your suggestion works 100%!, p-value=0.00001 :-)

And thanks again
for your *great Venn R pkg*.

RAY
*calintel*@gmail.com
*San Francisco*
*Rstudio/Ubuntu Linux 18.04 64bits*
---
