### ISSUE TITLE
Is there a way to plot the 2-set venn diagram "horizontally"?

### ISSUE THREAD

**Issue by gavieira** [gaospecial/ggVennDiagram#60]
Wondering if there is a way to plot it like this now:

![image](https://github.com/gaospecial/ggVennDiagram/assets/30009014/ea2a6bad-5996-49f0-9bc2-5366bcdec2c0)

**Comment by gaospecial** [comment]
Sorry for this inconvenience.

```r
genes <- paste0("gene",1:1000)
gene_list <- list(A = sample(genes,100),
                   B = sample(genes,200))

# construct a Venn object
venn = Venn(gene_list)
data = process_data(venn, shape_id = "201")
plot_venn(data)
```

![image](https://github.com/gaospecial/ggVennDiagram/assets/107597/89c4224f-8ec8-4fcf-8c30-16ad5c62ba8b)

**Comment by gavieira** [comment]
Thanks!! :)

**Comment by gaospecial** [comment]
I added a `shape_id` param in `ggVennDiagram()`, so it would be fine with `ggVennDiagram(x, shape_id = '201')`.
