### ISSUE TITLE
How to add the intersection Count value at the top of each UPSET plot

### ISSUE THREAD

**Issue by sfd99** [gaospecial/ggVennDiagram#63]
**_Hi Chun-Hui Gao_,

TRULY EXCELLENT PKG!** .

From you Github example,
using sets: **A**, **B**, **C** and **D**.

```
library(ggVennDiagram)
genes <- paste("gene",1:1000,sep="")
set.seed(20231214)
x <- list(A=sample(genes,300),
          B=sample(genes,525),
          C=sample(genes,440),
          D=sample(genes,350))
```
**Q**:
How to add the intersection Count values,
( for ex: 94 at B/C ),
_at the top of each vertical bar_ 
of the UPSET plot.

I tried:
ggVennDiagram(x[1:4], force_upset = TRUE,  order.set.by = "name",  order.intersect.by = "size")

which show fine,
but the _intersection count values_
are not shown 
at the top of each vertical bar...

![image](https://github.com/gaospecial/ggVennDiagram/assets/3316239/50a4b2cd-e63a-4b49-a225-46b277596209)

How to do that, simply?

_Thanks!_
**SFd99
latest R and Rstudio
Ubuntu Linux 20.04
ggVennDiagram version: 1.4.13  ( d/l and installed f/GITHUB ).
San Francisco.**

**Comment by gaospecial** [comment]
Sorry for the delay of reply. The new dev version should works. Please install with `pak::pak("gaospecial/ggVennDiagram")` and retry.

see <https://github.com/gaospecial/ggVennDiagram/commit/eaf9df973f5019a5908949c31506799e13ba4870>

**Comment by sfd99** [comment]
**_Hi Chun-Hui Gao_**

Super-perfect.
Thank you, 10^6 !...
