### ISSUE TITLE
Fill with custom variable instead of counts

### ISSUE THREAD

**Issue by fy711** [gaospecial/ggVennDiagram#67]
Hi,

Thanks for your fantastic package! I have a quick question about fill colors, and part of my data is like this:

| Member  | Set |  Variable |
| ------------- | ------------- | ------------- |
| a  | Set 1  | 0.25  |
| b  | Set 1, Set 2  | 0.35  |
| c  | Set 1, Set 2  | 0.45  |
| d  | Set 2  | 0.50  |

![Picture1](https://github.com/gaospecial/ggVennDiagram/assets/105269414/efca6d04-36cf-47a3-81c9-370e3c039c13)

As the picture shown above, instead of counts, can I use the values of 'Variable' column to fill each separate region? If there are multiple members in the same region (which is very likely), I'd like to take mean of Variable. Could you please advise me on how to achieve this? Thank you!

**Comment by gaospecial** [comment]
Thanks. Please refer to this vignette: https://gaospecial.github.io/ggVennDiagram/articles/fully-customed.html

**Comment by fy711** [comment]
> Thanks. Please refer to this vignette: https://gaospecial.github.io/ggVennDiagram/articles/fully-customed.html

Thank you! I'll take a close look at it and see if I can work this out.

**Comment by fy711** [comment]
Just to follow up on this issue, by modifying `new_data <- venn_regionedge(data)`, then plotting the venn diagram using `geom_polygon(aes(X, Y, fill = variable, group = id), data = new_data)` works for me. Thanks again for the help!
