### ISSUE TITLE
toggle for geom_text instead of geom_label (for ggplotly support)

### ISSUE THREAD

**Issue by joannawolthuis** [gaospecial/ggVennDiagram#7]
Hi there! I've been looking for a proper ggplot implementation of venn diagrams for a long time now, so thank you for this :) 
I make an app that can toggle between ggplot and plotly - and ideally in a venn diagram in plotly I'd like to be able to click an overlapping part and get all members of that overlap. So what that means is basically that I have two requests:
1. ggplotly doesn't support geom_label - would you consider switching to geom_text or adding an option to toggle to that?
2. would you be willing to add a 'key' aes to the plot that contains something akin to "Category1, Category2, Category3" that I could reference in ggplotly?

I'll take a look if I can make a pull request for it if I can get it working :) 

>  p = ggVennDiagram(x,label = "percent")
>  ggplotly(p)
> Warning message:
> In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
>   geom_GeomLabel() has yet to be implemented in plotly.
>   If you'd like to see this geom implemented,
>   Please open an issue with your example code at
>   https://github.com/ropensci/plotly/issues

**Comment by gaospecial** [comment]
Ggvenndiagram use `geom_label()` to draw transparent border in plot. Refer to `ggVennDiagram:::plot_venn()` if you would like to get it work.

**Comment by gaospecial** [comment]
@joannawolthuis ggVennDiagram now provides a `label_geom` parameter. Setting `label_geom = "text"` may be what you want to do.
