### ISSUE TITLE
Coloring venn_regionedge in custom plot

### ISSUE THREAD

**Issue by mauritsunkel** [gaospecial/ggVennDiagram#70]
Hi, I used to work with the geom_sf() functions, with the new version this doesn't seem to work anymore, could you tell me which version that was? 

For the newest version, I am using the code below to get custom coloring on the custom plot based on: https://gaospecial.github.io/ggVennDiagram/articles/fully-customed:

```
library(ggplot2)
library(ggVennDiagram)

col <- c("#ff00ff", "olivedrab", "#7f0000", "#4b0082", "#ff0000",
         "black", "#ffff00", "#00ff00", "#00fa9a", "#00ffff", "#0000ff",
         "darkslategray", "#6495ed", "#ffe4b5", "#ff69b4")
genes <- paste("gene",1:1000,sep="")
x <- list(
  A = sample(genes,300),
  B = sample(genes,525),
  C = sample(genes,440),
  D = sample(genes,350)
)
# ggVennDiagram(x, label_alpha = 0, label_color = "white", force_upset = F)

venn <- Venn(x)
d <- process_data(venn)
d$regionEdge$col <- plyr::mapvalues(
  d$regionEdge$id,
  unique(d$regionEdge$id),
  col
)

ggplot() +
  geom_polygon(aes(X, Y, fill = col, group = id), data = venn_regionedge(d), show.legend = F) +
  geom_path(aes(X, Y, color = id, group = id), data = venn_setedge(d), show.legend = F) +
  geom_text(aes(X, Y, label = name), fontface = "bold",data = venn_setlabel(d)) +
  geom_label(aes(X, Y, label = count), data = venn_regionlabel(d)) +
  coord_equal() +
  theme_void() + ggplot2::scale_x_continuous(expand = ggplot2::expansion(mult = .2))
```

I'm trying geom_polygon(aes(fill = col)) instead of geom_polygon(aes(fill = id)) based on the fully-customed example. I also tried + scale_color_manual(values = col). 

Could you advise on how to get the custom coloring working?

**Comment by gaospecial** [comment]
If you want to specify col in `geom_polygon()`, two methods can be used: 1) `I()` and 2) assign filling color with `scale_fill_manual()`. This is because the word of automatic mapping in `ggplot2` system.

```r

ggplot() +
  geom_polygon(aes(X, Y, fill = I(col), group = id), data = venn_regionedge(d), show.legend = F) +
  geom_path(aes(X, Y, color = id, group = id), data = venn_setedge(d), show.legend = F) +
  geom_text(aes(X, Y, label = name), fontface = "bold",data = venn_setlabel(d)) +
  geom_label(aes(X, Y, label = count), data = venn_regionlabel(d)) +
  coord_equal() +
  theme_void() + ggplot2::scale_x_continuous(expand = ggplot2::expansion(mult = .2))


ggplot() +
  geom_polygon(aes(X, Y, fill = id, group = id), data = venn_regionedge(d), show.legend = F) +
  geom_path(aes(X, Y, color = id, group = id), data = venn_setedge(d), show.legend = F) +
  geom_text(aes(X, Y, label = name), fontface = "bold",data = venn_setlabel(d)) +
  geom_label(aes(X, Y, label = count), data = venn_regionlabel(d)) +
  coord_equal() +
  scale_fill_manual(values = col) +
  theme_void() + ggplot2::scale_x_continuous(expand = ggplot2::expansion(mult = .2))
```

![image](https://github.com/user-attachments/assets/e57b9e64-fe20-444d-84d9-888b5b7dadbf)

**Comment by mauritsunkel** [comment]
Hi @gaospecial, thank you so much, both work! 

I just get different edges colored: 
![image](https://github.com/user-attachments/assets/743d5a4a-6338-4a89-8e36-242b8b008c5c)

I'll leave this here for others, and figure which one is best for me in this case.

**Comment by Andreas-Bio** [comment]
How can I supply 4 colors and have the overlaps calculated automatically?

**Comment by gaospecial** [comment]
> How can I supply 4 colors and have the overlaps calculated automatically?

Not supported.
