### ISSUE TITLE
Color by category?

### ISSUE THREAD

**Issue by zhanxw** [gaospecial/ggVennDiagram#9]
Is there a way I can specify colors for each category (not mapping the counts to color)?

e.g. category A is red with alpha = 30%, category B is green with alpha = 30%, category C is blue with alpha = 30%.
The final figure looks like this: 

https://scriptsandstatistics.files.wordpress.com/2018/05/unnamed-chunk-2-18.png?w=450&zoom=2

**Comment by gaospecial** [comment]
just use the `VennDiagram` package, by which you can specify fill color by eclipse.

here is an example:

```r
genes <- paste("gene",1:1000,sep="")
set.seed(20201126)
x <- list(A=sample(genes,300),B=sample(genes,525),C=sample(genes,440),D=sample(genes,350))
VennDiagram::venn.diagram(x, fill=c("blue","red","green","cyan"), alpha = 0.3, filename = "out.png")
```

![image](https://user-images.githubusercontent.com/107597/100335680-3adb6980-3010-11eb-888c-26d3ae0796db.png)


Note the order of ABCD in `VennDiagram` is different from `ggVennDiagram`.
